import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Delete44</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <h1>Hi, I'm Anthony...</h1>

          <small>He/Him</small>

          <p>Intro Text</p>

          <p>Intro text</p>
        </section>

        <section></section>
      </main>

      <footer>&copy; Anthony | Delete44</footer>
    </div>
  );
}
